### ISSUE TITLE
Clicking "Back" button should preserve relative position on page (as with other websites)

### ISSUE THREAD

**Issue by seanlip** [oppia/foundation-website#64]
Go to any website (e.g. do a google search), scroll down to about the middle, and click a link. When you click the back button, you are taken back to the place on the previous page where you clicked the link.

However, when clicking the back button on the Foundation site, you are instead taken to the top of the page. It would be better to preserve the existing behaviour on the web instead (of taking the user back to the place in the previous page where the link was clicked).

**Comment by hoangviet1993** [comment]
You know. I have been looking into this since this is a very fair request.

I first look into some sort of header-cache solution hoping for a quick fix. Like simply passing on a header somewhere. However, I think this requires some sort of template rendering, which I think we are trying to avoid.

Can you check if Google docs remember your scroll location?
https://docs.google.com/document/u/0/

**Comment by hoangviet1993** [comment]
https://stackoverflow.com/questions/14107531/retain-scroll-position-on-route-change-in-angularjs

Is this more or less what you are looking for?

**Comment by seanlip** [comment]
Yep, I think so. Haven't looked at implementation but the jsfiddle demo behaves well!
